### ISSUE TITLE
New include

### ISSUE THREAD

**Issue by StyXman** [amoghe/go-crypt#5]
For compiling this on Ubuntu 19.10 you must include a new include

```c
#include <stdlib.h>
```

See http://man7.org/linux/man-pages/man3/crypt.3.html

**Comment by StyXman** [comment]
This is fixed by #2.

**Comment by amoghe** [comment]
@StyXman  - I just tried compiling this in a ubuntu 19.10  environment, and it seems to work fine.

Can you give me steps where you ran into this failure?

**Comment by StyXman** [comment]
Given that you merged #2, this doesn't matter anymore.
